### PR TITLE
Fixed the errors on MAC OS

### PR DESCRIPTION
**Pull request by ShawnLess**
According to Éder's opinion, I preserved the "-Wconversion" option but deleted the "-Werror" option in the Makefile.  A lot of warnings generated but the program was successfully compiled and ran well.

the compilation command on my MAC is:
```
make XERCES_ROOT=/opt/local
```

### CODE REVIEW

**Comment by Sv3n** [comment]
I see the CI test didn't totally agree with the changes. I can have a look at this next week. Preferably I would like to put the right static_casts in the right places (or change datatypes such that we don't need them anymore).

@ShawnLess are you able to do whatever you were planning to do with DRAMPower as of now? If so, then I propose we leave this pull request open for now, such that I can work out a more robust fix.

**Comment by myzinsky** [comment]
@Sv3n: If you need help, I also have a mac ;) I think the main difference is that Mac uses clang as main compiler not gcc.

**Comment by ShawnLess** [comment]
@Sv3n : Not yet. I'm  planning to propose a new structure of DRAM and hope to estimate the power with DRAMPower, but the proposal is far from mature right now. 

The problem focuses on the "max" function template, which apparently differently implemented in Clang and GCC. I will check it on Ubuntu soon.

**Comment by myzinsky** [comment]
@ShawnLess: by the way, for new DRAM structures you should also look to our other tool, DRAMSpec: https://github.com/myzinsky/DRAMSpec

**Comment by ShawnLess** [comment]
@Sv3n Great, I will check that for sure.

I have just test the mac-patch branch on my Ubuntu, it is strange that all test have passed. The main difference between my Ubuntu and CI is the GCC version. 
```
xiesl@ubuntu:~/DRAMPower.git$ git branch -va
* mac-patch                     8688344 Fixed the errors when compiled on MAC OS
  master                        9345a5b Renamed test.
  remotes/origin/HEAD           -> origin/master
  remotes/origin/mac-patch      8688344 Fixed the errors when compiled on MAC OS
  remotes/origin/master         9345a5b Renamed test.
  remotes/origin/power_per_bank 0827d36 Restored tabs in test reference.
```
The Ubuntu version is:
```
xiesl@ubuntu:~/DRAMPower.git$ cat /etc/issue
Ubuntu 14.04.1 LTS \n \l
xiesl@ubuntu:~/DRAMPower.git$ uname -a
Linux ubuntu 3.13.0-71-generic #114-Ubuntu SMP Tue Dec 1 02:35:20 UTC 2015 i686 i686 i686 GNU/Linux
```
And GCC version is:
```
xiesl@ubuntu:~/DRAMPower.git$ gcc --version
gcc (Ubuntu 4.8.2-19ubuntu1) 4.8.2
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

```
xiesl@ubuntu:~/DRAMPower.git$ make test COVERAGE=1
xiesl@ubuntu:~/DRAMPower.git$ make test COVERAGE=1
unzip traces.zip && mkdir -p traces && mv DRAMPowerTraces-master/traces/* traces/ && rm -rf DRAMPowerTraces-master
Archive:  traces.zip
e640d3f7ff3766cdf4a799943f81e6ffe0946fb4
   creating: DRAMPowerTraces-master/
   creating: DRAMPowerTraces-master/traces/
  inflating: DRAMPowerTraces-master/traces/LICENSE  
  inflating: DRAMPowerTraces-master/traces/commands.trace  
  inflating: DRAMPowerTraces-master/traces/mediabench-epic.trace  
  inflating: DRAMPowerTraces-master/traces/mediabench-h263encode.trace  
  inflating: DRAMPowerTraces-master/traces/mediabench-jpegencode.trace  
  inflating: DRAMPowerTraces-master/traces/mediabench-mpeg2encode.trace  
python test/test.py -v
test_make_wo_args_completes_returns_0 (__main__.TestBuild)
'make -j4' should return 0 ... ok
test_make_clean_removes_compiler_output (__main__.TestClean)
'make clean' should remove all .o and .a and .d files ... ok
test_libdrampower_output_matches_reference (__main__.TestLibDRAMPower)
libdrampower-based executable output should match reference ... src/CmdScheduler.cc: In member function ‘void Data::cmdScheduler::schedulingInitialization(const Data::MemorySpecification&)’:
src/CmdScheduler.cc:87:16: warning: conversion to ‘std::vector<Data::cmdScheduler::commandItem>::size_type {aka unsigned int}’ from ‘long long int’ may alter its value [-Wconversion]
   ACT.resize(2 * memSpec.memArchSpec.nbrOfBanks);
....

src/CommandAnalysis.cc:114:40: warning: conversion to ‘std::vector<long long int>::size_type {aka unsigned int}’ from ‘int64_t {aka long long int}’ may alter its value [-Wconversion]
   activation_cycle.resize(nbrofBanks, 0);
                                        ^
ok
test_libdrampower_with_xerces_test_builds (__main__.TestLibDRAMPower)
libdrampower-based executable build should return 0 ... ok
test_libdrampower_without_xerces_test_builds (__main__.TestLibDRAMPower)
libdrampower-based executable build should return 0 ... ok
test_LPDDR2_1066_matches_reference (__main__.TestOutput)
drampower output for an LPDDR2-1066 trace matches reference ... ok
test_LPDDR2_1066_termination_matches_reference (__main__.TestOutput)
drampower output for an LPDDR2-1066 trace with termination power enabled matches reference ... ok
test_broken_trace (__main__.TestOutput)
running drampower with an invalid trace returns 0 ... ok
test_commands_trace_output_matches_reference (__main__.TestOutput)
drampower output for commands.trace example should be equal to test_commands_trace_output_matches_reference.out ... ok
test_no_arguments_error (__main__.TestOutput)
running drampower w/o arguments returns 1 ... ok
test_transaction_scheduler (__main__.TestOutput)
drampower output for LPDDR3-1333 with the jpegencode transaction trace matches reference ... ok
test_transaction_scheduler_with_self_refresh (__main__.TestOutput)
drampower output for LPDDR3-1333 with the jpegencode transaction trace matches reference ... ok

----------------------------------------------------------------------
Ran 12 tests in 65.462s

OK

**Comment by Sv3n** [comment]
I'll start by switching the compiler to clang and fixing the problems I encounter. Once I get a successful compile there, I'll push the changes, and then we should see if there are additional issues that are only visible on a real mac.

(Link to #29 )

**Comment by myzinsky** [comment]
Hi Sven,

I compiled it successfully by just removing the WError flag.
But I can directly try if it works on MAC

Regards
Matthias


--

Dipl.-Ing. Matthias Jung

Member
Advanced Silicon Technologies & Design Methodologies


University of Kaiserslautern
Microelectronic Systems Design Research Group
Erwin-Schrödinger-Straße 12/228
67663 Kaiserslautern, Germany

Phone: +49 631 205 3579
Fax: +49 631 205 4437
jungma@eit.uni-kl.de
http://ems.eit.uni-kl.de

**Comment by efzulian** [comment]
Hi Sven, I'm happy to say that the changes you've done for mac are not limited to mac and they fix also the compilation for gcc-5.2.1.

I did some tests on my laptop using gcc-5.2.1 and I am not able to compile the master branch because of the same (or at least very similar) issues related to casts and template/functions signatures.

My laptop:
```
$ uname -a && gcc --version
Linux eder-think 4.2.0-35-generic #40-Ubuntu SMP Tue Mar 15 19:53:28 UTC 2016 i686 i686 i686 GNU/Linux
gcc (Ubuntu 5.2.1-22ubuntu2) 5.2.1 20151010
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

On one of our servers using gcc-4.8.2 the master branch compiles out of the box.

```
$ uname -a && gcc --version
Linux dram.eit.uni-kl.de 2.6.32-573.18.1.el6.x86_64 #1 SMP Tue Feb 9 22:46:17 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
gcc (GCC) 4.8.2
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

The mac branch compiles without errors on my laptop. So the fixes in the mac branch are also good for gcc-5.2.1. ;)

Regards,
Éder

**Comment by efzulian** [comment]
Hi Sven,
if you need some help for doing some tests I'm a volunteer. ;)
I can run tests with gcc-5.2.1 on my Ubuntu and also with gcc-4.8.2 on a server.
Please just let me know how I can help.
Regards,
Éder

**Comment by Sv3n** [comment]
Hey Éder, good to head these changes are useful. I intend to merge the mac branch into the master, after I have some time to think about the changes I made related to issue #32, and after we merge in the changes related to #31 . If you would like to help in testing, then it would be interesting to know if `make test` succeeds with the compilers you use, and if any of your own tests act as you expect.

For now, I will close this pull request, since the mac branch has superseded it. I propose to continue the discussion on #32 if required.

**Comment by efzulian** [comment]
Regarding the tests, I posted the details in #29

**Pull request closed without merging**
