### PR TITLE
Power of individual banks

### PR DESCRIPTION
**Pull request by efzulian**
Summary of changes:

Implement bank-wise refresh.

Bank-wise ACT and PRE energy calculations are updated with new formulas as below.

```
Ione := ( Idd3n + [ ρ.(Idd3n - Idd2n) + Idd2n ].(B - 1) )
	     ------------------------------------------------
	                       B

Eact(b) = Vdd.[ Idd0 - Ione ].tRAS.Nact(b)
Epre(b) = Vdd.[ Idd0 - Ione ].tRP.Npre(b)
```

Add new modified spec (modified_MICRON_1Gb_DDR3-1600_8bit_G_3s.xml) with REFB parameters idd5b and tREFB.

Add unit test for REFB calculation.

Implement bank-wise energy distribution for the below components.

```
idle_energy_act
idle_energy_pre
f_act_pd_energy
f_pre_pd_energy
s_act_pd_energy
s_pre_pd_energy
sref_energy
sref_ref_energy
sref_ref_act_energy
sref_ref_pre_energy
spup_energy
spup_ref_energy
spup_ref_act_energy
spup_ref_pre_energy
pup_act_energy
pup_pre_energy
```

New class for bank-wise parameters.

Implement explicit handling of PASR and Self-Refresh power factor Sigma. CLI arguments added.

Added specs for SAMSUNG K4B1G1646E 1Gb DDR3-1600 16bit device.

Small improvements to the README file.

Bank-wise unit tests added.

This topic was discussed in the issue #28.

### CODE REVIEW

**Comment by efzulian** [comment]
@myzinsky could you please post some information about the publication where more information can be found? Thanks!

**Comment by myzinsky** [comment]
Here is the paper:

https://ems.eit.uni-kl.de/fileadmin/ems/user_upload/PID4374359.pdf

**Comment by Sv3n** [comment]
That's a lot of reading material :)

I'm happy it can be merged w/o conflicts, thanks for taking care of that. I'll probably get around to looking through the code over the weekend, and then I'll push the merge button.

**Comment by Sv3n** [comment]
Hi all!

I've had a look at the code, and will merge it in after typing this message. Apart from some code style issues, I have no remarks, and I do not want to nitpick right now.

In general, the code feels a bit copy-paste oriented, and I think we are forced into that style by the way our data structures are set up. I'm (slowly) working on some restructuring on a branch that should hopefully fix that to a large extent. I'll merge the changes from master into that branch later, to see if the new insight that we require statistics per bank changes the structure I had in mind.

**Comment by efzulian** [comment]
Hi Sven, thanks!
For the next commits we're going to be more careful with coding style.

**Pull request merged**
